# Generated by Django 2.1.5 on 2021-11-18 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mymart', '0002_offer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image_urls',
            new_name='image_url',
        ),
    ]
